version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Swashbuckle.AspNetCore.SwaggerUI
    versions:
    - 5.6.3
    - 6.0.2
    - 6.0.4
    - 6.0.5
    - 6.0.7
    - 6.1.0
    - 6.1.1
    - 6.1.2
  - dependency-name: Swashbuckle.AspNetCore.SwaggerGen
    versions:
    - 5.6.3
    - 6.0.2
    - 6.0.4
    - 6.0.5
    - 6.0.7
    - 6.1.0
    - 6.1.1
    - 6.1.2
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: coverlet.collector
    versions:
    - 3.0.2
  - dependency-name: Polly
    versions:
    - 7.2.1
  - dependency-name: Microsoft.AspNetCore.Mvc.Versioning
    versions:
    - 4.2.0
